[en]
  languageName = "English"
  contentDir = "content/en"
  weight = 10
  [en.params]
    languageISO = "EN"
    languageTag = "en-US"
    footer = '<a class="text-muted" href="https://sectrs.ethz.ch/">Secure and Trustworthy Systems Group</a>'
    alertText = 'We are at the <a class="alert-link " href="/docs/showcase/presentations/#open-confidental-computing-conference-2026">Open Confidental Computing Conference 2026</a>'
