on:
  push:
    branches:
      - master

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

name: build-website
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: '20.x'

    - name: Build webapp
      run: |
        make init
        rm -rf ./public/
        mkdir ./public
        make build

    - name: commit to github pages
      uses: peaceiris/actions-gh-pages@v4
      # If you're changing the branch from main,
      # also change the `master` in `refs/heads/master`
      # below accordingly.
      if: ${{ github.ref == 'refs/heads/opencca/main' }}
      with:
        deploy_key: ${{ secrets.OPENCCA_GITHUB_PAGES_SSH_KEY }}
        publish_dir: ./public/
        force_orphan: true
